import React, { Component } from "react";
import "./welcome.css";

export class Welcome extends Component {
  public render() {
    return (
      <div className="welcome">
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
        Maya Weissman
        <br />
      </div>
    );
  }
}
